[build]
  command = "npm run build"
  # هذا يحدد أن Netlify يجب أن تبحث عن المخرجات في مجلد "out"
  publish = "out"  

# هذا التوجيه (الذي عملنا عليه سابقاً) ضروري لحل مشكلة 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200